#include <stdio.h>
#include <stdlib.h>

//REVISÃO FINAL PARA A PROVA #02
//---- SISTEMA ACADÊMICO -------

//1 - CADASTRAR ALUNO
	//MATRICULA(I: AUTOINCREMENTO) 
	//NOME(S)

//2 - CADASTRAR DISCIPLINA
	//CODIGO(I: AUTOINCREMENTO)
	//NOME(S)
	//PERIODO(I)
	//MATRICULAS(I[50])

//3 - MATRICULAR ALUNO
	//MATRICULAR UM ALUNO EM UMA DETERMINADA DISCIPLINA
	//BUSCAR DISCIPLINA E ALUNO ATRAVÉS DE NOMES.
	//SOMENTE 1 MATRICULA POR ALUNO/DISCIPLINA (VALIDAR!)

//4 - CANCELAR MATRICULA (EXCLUIR MATRICULA)
	//EXCLUIR A MATRICULA DE UM DETERMINADO ALUNO 
	//EM UMA DISCIPLINA.

//5 - FAZER CHAMADA
	//SOLICITAR NOME DE DISCIPLINA.
	//LISTAR (EM ORDEM ALFABETICA) OS NOMES DOS ALUNOS
	//MATRICULADOS.
	//NÃO É NECESSÁRIO SALVAR DADOS. APENAS LISTAGEM.

//6 - HISTORICO DO ALUNO
	//SOLICITAR NOME DO ALUNO.
	//LISTAR TODAS AS DISCIPLINAS MATRICULADAS
	//(EM ORDEM DE PERIODO)
	//NÃO É NECESSÁRIO SALVAR DADOS. APENAS LISTAGEM.


void func(int alvo, int v[],int c){
	for(int i=0; i<c; i++)
		if(alvo == v[i])
			for(int j=i; j<c-1; j++)
				v[j] = v[j+1];
}

int main(){
}
